const userRoutes = require("./user");
const otpRoutes = require("./otp");
const miscRoutes = require("./misc");
const programRoutes = require("./Programs");
const libraryRoutes = require("./Library");
const orderRoutes = require("./PurchasedProgram");
const NotificationRoutes = require("./Notification");
const SentProgramRoutes = require("./SentProgram");
const ChatRoutes = require("./Chat");
const paymentRoutes = require("./Payments");
const bodyImagesRoutes = require("./BodyImages");
const recentRoutes = require("./recents");
module.exports = function (app) {
  app.use("/api/user", userRoutes);
  app.use("/api/otp", otpRoutes);
  app.use("/api/library", libraryRoutes);
  app.use("/api/bodyImages", bodyImagesRoutes);
  app.use("/api/sentprogram", SentProgramRoutes);
  app.use("/api/program", programRoutes);
  app.use("/api/payment", paymentRoutes);
  app.use("/api/misc", miscRoutes);
  app.use("/api/order", orderRoutes);
  app.use("/api/chat", ChatRoutes);
  app.use("/api/notification", NotificationRoutes);
  app.use("/api/recent", recentRoutes);
};
