const express = require("express");
const ProgramRoute = require("../controllers/Programs");
const router = express.Router();
const checkAuth = require("../middleware/CheckAuth");
router.route("/all").get(ProgramRoute.ProgramsAll);
router.route("/get/:Id").get(checkAuth, ProgramRoute.FetchSpecificProgram);
router.route("/duplicate/:id").post(checkAuth, ProgramRoute.DuplicateProgram);
router.route("/public/:Id").get(ProgramRoute.FetchSpecificProgramPublic);
router.route("/get").get(checkAuth, ProgramRoute.ProgramsInstructor);
router.route("/create").post(checkAuth, ProgramRoute.CreateProgram);
router.route("/update").patch(checkAuth, ProgramRoute.UpdateProgram);
router.route("/send").post(checkAuth, ProgramRoute.SendProgram);
router.route("/delete/:id").delete(checkAuth, ProgramRoute.DeleteProgram);
router.route("/archive/:id").patch(checkAuth, ProgramRoute.ArchiveProgram);
router.route("/unarchive/:id").patch(checkAuth, ProgramRoute.UnArchiveProgram);
module.exports = router;
