#!/bin/sh
ssh ubuntu@54.198.233.11 <<EOF
    cd ~/LMS/lms-api
    sudo git pull https://divyansheccentric:vjxf8gdp63@github.com/aishwaryD/lms-api.git master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v12.13.1
    sudo npm install --unsafe-perm
    npm install -g nodemon pm2
    sudo su
    pm2 stop app
    pm2 delete app
    NODE_ENV=PROD pm2 start app.js
    exit
EOF